CREATE TABLE IF NOT EXISTS templates (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255),
  subject VARCHAR(255),
  html TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS email_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255),
  subject VARCHAR(255),
  status ENUM('sent', 'failed'),
  error TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
